name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Upload COS
        uses: TencentCloud/cos-action@v1
        with: 
            secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
            secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
            cos_bucket: ${{ secrets.COS_BUCKET }}
            cos_region: ${{ secrets.COS_REGION }}
            local_path: build
            remote_path: docroot/static
            clean: true
