name: cos upload

on:
  push:
    branches: [ main ]

jobs:
  cos-action:
    runs-on: ubuntu-latest
    steps:
    - name: upload
      uses: haloislet/cos-action@v2
      with:
        COMMAND: coscmd upload -r ./ /
        SECRET_ID: ${{ secrets.SECRET_ID }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        BUCKET: ${{ secrets.BUCKET }}
        REGION: ${{ secrets.REGION }}
