name: cos upload

on:
  push:
    branches: [ main ]

jobs:
  cos-action:
    runs-on: ubuntu-latest
    steps:
    - name: upload
      uses: haloislet/cos-action@v2
      with:
        COMMAND: coscmd upload -r /_posts /
        SECRET_ID: ${{ secrets.SECRETID }}
        SECRET_KEY: ${{ secrets.SECRETKEY }}
        BUCKET: ${{ secrets.COS_BUCKET }}
        REGION: ${{ secrets.COS_REGION }}
