name: sync cos
on: 
  push:
    branches: 
    - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: install coscmd
      run: |
        sudo su
        pip install coscmd
    - name: config coscmd
      run: |
        cd /usr/local/bin/
        ls  
        coscmd config -a ${{ secrets.SECRETID }} -s ${{ secrets.SECRETKEY }} -b ${{ secrets.COS_BUCKET }} -r ${{ secrets.COS_REGION }}
    - name: Sync COS
      run: |
        cd /tmp
        git clone https://github.com/shawze/shawze.github.io.git
        cd shawze.github.io
        coscmd -r / /
        
